export const DATABASES_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const SUBSCRIPTION_ID =
    process.env.NEXT_PUBLIC_APPWRITE_SUBSCRIPTIONS_ID!;
export const USER_TARGET_EMAIL_ID =
    process.env.NEXT_PUBLIC_APPWRITE_USER_TARGET_EMAIL_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_STORAGE_ID!;
