import { env } from "@/lib/env";

export const DATABASES_ID = env.APPWRITE_DATABASE_ID;
export const WORKSPACES_ID = env.APPWRITE_WORKSPACES_ID;
export const MEMBERS_ID = env.APPWRITE_MEMBERS_ID;
export const PROJECTS_ID = env.APPWRITE_PROJECTS_ID;
export const TASKS_ID = env.APPWRITE_TASKS_ID;
export const SUBSCRIPTION_ID = env.APPWRITE_SUBSCRIPTIONS_ID;
export const USER_TARGET_EMAIL_ID = env.APPWRITE_USER_TARGET_EMAIL_ID;
export const IMAGES_BUCKET_ID = env.APPWRITE_STORAGE_ID;
